### PR TITLE
Dispersion

### PR DESCRIPTION
**Pull request by ajhoffman1229**
## Summary

Major changes:

- tutorial: added a python notebook tutorial showing users how to add a dispersion correction to the main CHGNet model. Approving this would address #188 .

## Checklist

This PR would not add any new features to the core code and only contains a notebook showing how to add dispersion to the CHGNet calculator through ASE. I installed pre-commit hooks and used them to format the code in the notebook.

- [x] All existing tests pass.
- [x] Tests have been added for any new features/fixes.
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

### CODE REVIEW

**Review by janosh — CHANGES_REQUESTED** [review]
after `pip install torch_dftd dftd4`, `examples/dispersion.ipynb` doesn't run for me. getting a kernel crash from the import cell:

Screenshot 2024-08-24 at 06 57 10

**Comment by ajhoffman1229** [comment]
I am not sure that DFT-D4 has a module available on pypi, you may need to use `conda` or `mamba`. Can you also install the python extension of DFT-D4? I think you will need `conda install dftyd4 dftd4-python -c conda-forge` per the instructions [here](https://dftd4.readthedocs.io/en/latest/recipe/installation.html). I remember having a similar issue before when I installed the base `dftd4` package without the `dftd4-python` component and tried to import DFT-D4. Without the python part, the import will fail.

Also, did you run `pip install torch_dftd` or `pip install torch-dftd`? I believe the latter is what is [listed on pypi](https://pypi.org/project/torch-dftd/) and I'm not sure the installation will work with an underscore.

**Comment by janosh** [comment]
> I am not sure that DFT-D4 has a module available on pypi, you may need to use conda or mamba.

i see. not a fan of `conda` or `mamba` (strongly prefer `uv`). but that's not a blocker PR ofc, esp. for an optional dep. @BowenD-UCB you wanna try running the notebook? else happy to merge as is.

PS: `pip install torch-dftd` and `pip install torch_dftd` are equivalent.

**Comment by ajhoffman1229** [comment]
> > I am not sure that DFT-D4 has a module available on pypi, you may need to use conda or mamba.
> 
> i see. not a fan of `conda` or `mamba` (strongly prefer `uv`). but that's not a blocker PR ofc, esp. for an optional dep. @BowenD-UCB you wanna try running the notebook? else happy to merge as is.
> 
> PS: `pip install torch-dftd` and `pip install torch_dftd` are equivalent.

I had not heard of `uv` before but I can understand the appeal, thank you for sharing! I like the idea of a rust-based environment manager.

**Comment by BowenD-UCB** [comment]
Hi @ajhoffman1229 and @janosh 
Thanks for the PR!
Sorry for the delay on this.
I tried to install these extra dependencies but encountered installation issue (package incompatibilities) with `dftd4-python`
As these are optional deps I'll merge as it is now.

**Pull request merged**
