### PR TITLE
1. Fixed units of taut, taup 2. Added missing ttime in NPT

### PR DESCRIPTION
**Pull request by tsihyoung**

### CODE REVIEW

**Comment by janosh** [comment]
Thanks, could you add a unit test?

**Comment by tsihyoung** [comment]
> Thanks, could you add a unit test?

This PR can still pass the original `test_md.py`. To make the difference caused by `taut` and `taup` observable, MD simulation duration should be longer.

Another thing is that for each run, Ekin can deviate up to 2e-3 relatively. This high threshold might cause false positive in testing.

For Nose-Hoover part, `ase` is buggy when external stress is not given. I have also made a PR there. It might be better to add a unit test for N-H later?

**Comment by BowenD-UCB** [comment]
Thanks for fixing this, there is indeed a bug that we passed taut with unit of units.fs**2 to berendsen thermostat.

**Comment by BowenD-UCB** [comment]
The Nose-Hoover thermostat is just added. Currently the ASE implementation only supports upper triangular lattice, with no numerical tolerance. As a result it's not useful at this point, and we have only tested it prelimineraily. The transformation of lattice to upper-triagngular matrix will be implemented later

**Review by BowenD-UCB — APPROVED** [review]

**Pull request merged**
